services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_DSN: "postgresql://postgres:password@db:5432/postgres"
    depends_on:
      - db
    ports:
      - "8080:80"

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
